// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file grsim/grSim_Replacement.proto (package grSim, syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grsim/grSim_Replacement.proto.
 */
export const file_grsim_grSim_Replacement: GenFile = /*@__PURE__*/
  fileDesc("Ch1ncnNpbS9nclNpbV9SZXBsYWNlbWVudC5wcm90bxIFZ3JTaW0iUQoVZ3JTaW1fQmFsbFJlcGxhY2VtZW50EgwKAXgYASABKAE6ATASDAoBeRgCIAEoAToBMBINCgJ2eBgDIAEoAToBMBINCgJ2eRgEIAEoAToBMCJrChZnclNpbV9Sb2JvdFJlcGxhY2VtZW50EgkKAXgYASACKAESCQoBeRgCIAIoARILCgNkaXIYAyACKAESCgoCaWQYBCACKA0SEgoKeWVsbG93dGVhbRgFIAIoCBIOCgZ0dXJub24YBiABKAgibgoRZ3JTaW1fUmVwbGFjZW1lbnQSKgoEYmFsbBgBIAEoCzIcLmdyU2ltLmdyU2ltX0JhbGxSZXBsYWNlbWVudBItCgZyb2JvdHMYAiADKAsyHS5nclNpbS5nclNpbV9Sb2JvdFJlcGxhY2VtZW50Qo8BCgljb20uZ3JTaW1CFUdyU2ltUmVwbGFjZW1lbnRQcm90b1ABWjdnaXRodWIuY29tL1JvYm9DdXAtU1NML3NzbC12aXNpb24tY2xpZW50L2ludGVybmFsL2dyc2ltogIDR1hYqgIFR3JTaW3KAgVHclNpbeICEUdyU2ltXEdQQk1ldGFkYXRh6gIFR3JTaW0");

/**
 * @generated from message grSim.grSim_BallReplacement
 */
export type grSim_BallReplacement = Message<"grSim.grSim_BallReplacement"> & {
  /**
   * @generated from field: optional double x = 1 [default = 0];
   */
  x: number;

  /**
   * @generated from field: optional double y = 2 [default = 0];
   */
  y: number;

  /**
   * @generated from field: optional double vx = 3 [default = 0];
   */
  vx: number;

  /**
   * @generated from field: optional double vy = 4 [default = 0];
   */
  vy: number;
};

/**
 * @generated from message grSim.grSim_BallReplacement
 */
export type grSim_BallReplacementJson = {
  /**
   * @generated from field: optional double x = 1 [default = 0];
   */
  x?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional double y = 2 [default = 0];
   */
  y?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional double vx = 3 [default = 0];
   */
  vx?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional double vy = 4 [default = 0];
   */
  vy?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message grSim.grSim_BallReplacement.
 * Use `create(grSim_BallReplacementSchema)` to create a new message.
 */
export const grSim_BallReplacementSchema: GenMessage<grSim_BallReplacement, grSim_BallReplacementJson> = /*@__PURE__*/
  messageDesc(file_grsim_grSim_Replacement, 0);

/**
 * @generated from message grSim.grSim_RobotReplacement
 */
export type grSim_RobotReplacement = Message<"grSim.grSim_RobotReplacement"> & {
  /**
   * @generated from field: required double x = 1;
   */
  x: number;

  /**
   * @generated from field: required double y = 2;
   */
  y: number;

  /**
   * @generated from field: required double dir = 3;
   */
  dir: number;

  /**
   * @generated from field: required uint32 id = 4;
   */
  id: number;

  /**
   * @generated from field: required bool yellowteam = 5;
   */
  yellowteam: boolean;

  /**
   * @generated from field: optional bool turnon = 6;
   */
  turnon: boolean;
};

/**
 * @generated from message grSim.grSim_RobotReplacement
 */
export type grSim_RobotReplacementJson = {
  /**
   * @generated from field: required double x = 1;
   */
  x?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required double y = 2;
   */
  y?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required double dir = 3;
   */
  dir?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required uint32 id = 4;
   */
  id?: number;

  /**
   * @generated from field: required bool yellowteam = 5;
   */
  yellowteam?: boolean;

  /**
   * @generated from field: optional bool turnon = 6;
   */
  turnon?: boolean;
};

/**
 * Describes the message grSim.grSim_RobotReplacement.
 * Use `create(grSim_RobotReplacementSchema)` to create a new message.
 */
export const grSim_RobotReplacementSchema: GenMessage<grSim_RobotReplacement, grSim_RobotReplacementJson> = /*@__PURE__*/
  messageDesc(file_grsim_grSim_Replacement, 1);

/**
 * @generated from message grSim.grSim_Replacement
 */
export type grSim_Replacement = Message<"grSim.grSim_Replacement"> & {
  /**
   * @generated from field: optional grSim.grSim_BallReplacement ball = 1;
   */
  ball?: grSim_BallReplacement;

  /**
   * @generated from field: repeated grSim.grSim_RobotReplacement robots = 2;
   */
  robots: grSim_RobotReplacement[];
};

/**
 * @generated from message grSim.grSim_Replacement
 */
export type grSim_ReplacementJson = {
  /**
   * @generated from field: optional grSim.grSim_BallReplacement ball = 1;
   */
  ball?: grSim_BallReplacementJson;

  /**
   * @generated from field: repeated grSim.grSim_RobotReplacement robots = 2;
   */
  robots?: grSim_RobotReplacementJson[];
};

/**
 * Describes the message grSim.grSim_Replacement.
 * Use `create(grSim_ReplacementSchema)` to create a new message.
 */
export const grSim_ReplacementSchema: GenMessage<grSim_Replacement, grSim_ReplacementJson> = /*@__PURE__*/
  messageDesc(file_grsim_grSim_Replacement, 2);

