// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file grsim/grSim_Commands.proto (package grSim, syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grsim/grSim_Commands.proto.
 */
export const file_grsim_grSim_Commands: GenFile = /*@__PURE__*/
  fileDesc("ChpncnNpbS9nclNpbV9Db21tYW5kcy5wcm90bxIFZ3JTaW0i6gEKE2dyU2ltX1JvYm90X0NvbW1hbmQSCgoCaWQYASACKA0SEgoKa2lja3NwZWVkeBgCIAIoAhISCgpraWNrc3BlZWR6GAMgAigCEhIKCnZlbHRhbmdlbnQYBCACKAISEQoJdmVsbm9ybWFsGAUgAigCEhIKCnZlbGFuZ3VsYXIYBiACKAISDwoHc3Bpbm5lchgHIAIoCBITCgt3aGVlbHNzcGVlZBgIIAIoCBIOCgZ3aGVlbDEYCSABKAISDgoGd2hlZWwyGAogASgCEg4KBndoZWVsMxgLIAEoAhIOCgZ3aGVlbDQYDCABKAIibQoOZ3JTaW1fQ29tbWFuZHMSEQoJdGltZXN0YW1wGAEgAigBEhQKDGlzdGVhbXllbGxvdxgCIAIoCBIyCg5yb2JvdF9jb21tYW5kcxgDIAMoCzIaLmdyU2ltLmdyU2ltX1JvYm90X0NvbW1hbmRCjAEKCWNvbS5nclNpbUISR3JTaW1Db21tYW5kc1Byb3RvUAFaN2dpdGh1Yi5jb20vUm9ib0N1cC1TU0wvc3NsLXZpc2lvbi1jbGllbnQvaW50ZXJuYWwvZ3JzaW2iAgNHWFiqAgVHclNpbcoCBUdyU2lt4gIRR3JTaW1cR1BCTWV0YWRhdGHqAgVHclNpbQ");

/**
 * @generated from message grSim.grSim_Robot_Command
 */
export type grSim_Robot_Command = Message<"grSim.grSim_Robot_Command"> & {
  /**
   * @generated from field: required uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: required float kickspeedx = 2;
   */
  kickspeedx: number;

  /**
   * @generated from field: required float kickspeedz = 3;
   */
  kickspeedz: number;

  /**
   * @generated from field: required float veltangent = 4;
   */
  veltangent: number;

  /**
   * @generated from field: required float velnormal = 5;
   */
  velnormal: number;

  /**
   * @generated from field: required float velangular = 6;
   */
  velangular: number;

  /**
   * @generated from field: required bool spinner = 7;
   */
  spinner: boolean;

  /**
   * @generated from field: required bool wheelsspeed = 8;
   */
  wheelsspeed: boolean;

  /**
   * @generated from field: optional float wheel1 = 9;
   */
  wheel1: number;

  /**
   * @generated from field: optional float wheel2 = 10;
   */
  wheel2: number;

  /**
   * @generated from field: optional float wheel3 = 11;
   */
  wheel3: number;

  /**
   * @generated from field: optional float wheel4 = 12;
   */
  wheel4: number;
};

/**
 * @generated from message grSim.grSim_Robot_Command
 */
export type grSim_Robot_CommandJson = {
  /**
   * @generated from field: required uint32 id = 1;
   */
  id?: number;

  /**
   * @generated from field: required float kickspeedx = 2;
   */
  kickspeedx?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float kickspeedz = 3;
   */
  kickspeedz?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float veltangent = 4;
   */
  veltangent?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float velnormal = 5;
   */
  velnormal?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float velangular = 6;
   */
  velangular?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required bool spinner = 7;
   */
  spinner?: boolean;

  /**
   * @generated from field: required bool wheelsspeed = 8;
   */
  wheelsspeed?: boolean;

  /**
   * @generated from field: optional float wheel1 = 9;
   */
  wheel1?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional float wheel2 = 10;
   */
  wheel2?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional float wheel3 = 11;
   */
  wheel3?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional float wheel4 = 12;
   */
  wheel4?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message grSim.grSim_Robot_Command.
 * Use `create(grSim_Robot_CommandSchema)` to create a new message.
 */
export const grSim_Robot_CommandSchema: GenMessage<grSim_Robot_Command, grSim_Robot_CommandJson> = /*@__PURE__*/
  messageDesc(file_grsim_grSim_Commands, 0);

/**
 * @generated from message grSim.grSim_Commands
 */
export type grSim_Commands = Message<"grSim.grSim_Commands"> & {
  /**
   * @generated from field: required double timestamp = 1;
   */
  timestamp: number;

  /**
   * @generated from field: required bool isteamyellow = 2;
   */
  isteamyellow: boolean;

  /**
   * @generated from field: repeated grSim.grSim_Robot_Command robot_commands = 3;
   */
  robotCommands: grSim_Robot_Command[];
};

/**
 * @generated from message grSim.grSim_Commands
 */
export type grSim_CommandsJson = {
  /**
   * @generated from field: required double timestamp = 1;
   */
  timestamp?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required bool isteamyellow = 2;
   */
  isteamyellow?: boolean;

  /**
   * @generated from field: repeated grSim.grSim_Robot_Command robot_commands = 3;
   */
  robotCommands?: grSim_Robot_CommandJson[];
};

/**
 * Describes the message grSim.grSim_Commands.
 * Use `create(grSim_CommandsSchema)` to create a new message.
 */
export const grSim_CommandsSchema: GenMessage<grSim_Commands, grSim_CommandsJson> = /*@__PURE__*/
  messageDesc(file_grsim_grSim_Commands, 1);

