// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file grsim/grSim_Packet.proto (package grSim, syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { grSim_Replacement, grSim_ReplacementJson } from "./grSim_Replacement_pb";
import { file_grsim_grSim_Replacement } from "./grSim_Replacement_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grsim/grSim_Packet.proto.
 */
export const file_grsim_grSim_Packet: GenFile = /*@__PURE__*/
  fileDesc("ChhncnNpbS9nclNpbV9QYWNrZXQucHJvdG8SBWdyU2ltIj0KDGdyU2ltX1BhY2tldBItCgtyZXBsYWNlbWVudBgBIAEoCzIYLmdyU2ltLmdyU2ltX1JlcGxhY2VtZW50QooBCgljb20uZ3JTaW1CEEdyU2ltUGFja2V0UHJvdG9QAVo3Z2l0aHViLmNvbS9Sb2JvQ3VwLVNTTC9zc2wtdmlzaW9uLWNsaWVudC9pbnRlcm5hbC9ncnNpbaICA0dYWKoCBUdyU2ltygIFR3JTaW3iAhFHclNpbVxHUEJNZXRhZGF0YeoCBUdyU2lt", [file_grsim_grSim_Replacement]);

/**
 * @generated from message grSim.grSim_Packet
 */
export type grSim_Packet = Message<"grSim.grSim_Packet"> & {
  /**
   * @generated from field: optional grSim.grSim_Replacement replacement = 1;
   */
  replacement?: grSim_Replacement;
};

/**
 * @generated from message grSim.grSim_Packet
 */
export type grSim_PacketJson = {
  /**
   * @generated from field: optional grSim.grSim_Replacement replacement = 1;
   */
  replacement?: grSim_ReplacementJson;
};

/**
 * Describes the message grSim.grSim_Packet.
 * Use `create(grSim_PacketSchema)` to create a new message.
 */
export const grSim_PacketSchema: GenMessage<grSim_Packet, grSim_PacketJson> = /*@__PURE__*/
  messageDesc(file_grsim_grSim_Packet, 0);

