// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file sslsim/ssl_simulation_control.proto (package sslsim, syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sslsim/ssl_simulation_control.proto.
 */
export const file_sslsim_ssl_simulation_control: GenFile = /*@__PURE__*/
  fileDesc("CiNzc2xzaW0vc3NsX3NpbXVsYXRpb25fY29udHJvbC5wcm90bxIGc3Nsc2ltIj0KDVNzbFNpbVJvYm90SWQSCgoCaWQYASABKA0SIAoEdGVhbRgCIAEoDjISLnNzbHNpbS5Tc2xTaW1UZWFtIqEBCgxUZWxlcG9ydEJhbGwSCQoBeBgBIAEoAhIJCgF5GAIgASgCEgkKAXoYAyABKAISCgoCdngYBCABKAISCgoCdnkYBSABKAISCgoCdnoYBiABKAISHgoPdGVsZXBvcnRfc2FmZWx5GAcgASgIOgVmYWxzZRITCgRyb2xsGAggASgIOgVmYWxzZRIXCghieV9mb3JjZRgJIAEoCDoFZmFsc2UivQEKDVRlbGVwb3J0Um9ib3QSIQoCaWQYASACKAsyFS5zc2xzaW0uU3NsU2ltUm9ib3RJZBIJCgF4GAIgASgCEgkKAXkYAyABKAISEwoLb3JpZW50YXRpb24YBCABKAISDgoDdl94GAUgASgCOgEwEg4KA3ZfeRgGIAEoAjoBMBIUCgl2X2FuZ3VsYXIYByABKAI6ATASDwoHcHJlc2VudBgIIAEoCBIXCghieV9mb3JjZRgJIAEoCDoFZmFsc2UiiAEKEFNpbXVsYXRvckNvbnRyb2wSKwoNdGVsZXBvcnRfYmFsbBgBIAEoCzIULnNzbHNpbS5UZWxlcG9ydEJhbGwSLQoOdGVsZXBvcnRfcm9ib3QYAiADKAsyFS5zc2xzaW0uVGVsZXBvcnRSb2JvdBIYChBzaW11bGF0aW9uX3NwZWVkGAMgASgCIj0KEFNpbXVsYXRvckNvbW1hbmQSKQoHY29udHJvbBgBIAEoCzIYLnNzbHNpbS5TaW11bGF0b3JDb250cm9sKi8KClNzbFNpbVRlYW0SCwoHVU5LTk9XThAAEgoKBllFTExPVxABEggKBEJMVUUQAkKZAQoKY29tLnNzbHNpbUIZU3NsU2ltdWxhdGlvbkNvbnRyb2xQcm90b1ABWjhnaXRodWIuY29tL1JvYm9DdXAtU1NML3NzbC12aXNpb24tY2xpZW50L2ludGVybmFsL3NzbHNpbaICA1NYWKoCBlNzbHNpbcoCBlNzbHNpbeICElNzbHNpbVxHUEJNZXRhZGF0YeoCBlNzbHNpbQ");

/**
 * ロボットの識別子（gameController.BotId と同一のワイヤーフォーマット）
 *
 * @generated from message sslsim.SslSimRobotId
 */
export type SslSimRobotId = Message<"sslsim.SslSimRobotId"> & {
  /**
   * @generated from field: optional uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional sslsim.SslSimTeam team = 2;
   */
  team: SslSimTeam;
};

/**
 * ロボットの識別子（gameController.BotId と同一のワイヤーフォーマット）
 *
 * @generated from message sslsim.SslSimRobotId
 */
export type SslSimRobotIdJson = {
  /**
   * @generated from field: optional uint32 id = 1;
   */
  id?: number;

  /**
   * @generated from field: optional sslsim.SslSimTeam team = 2;
   */
  team?: SslSimTeamJson;
};

/**
 * Describes the message sslsim.SslSimRobotId.
 * Use `create(SslSimRobotIdSchema)` to create a new message.
 */
export const SslSimRobotIdSchema: GenMessage<SslSimRobotId, SslSimRobotIdJson> = /*@__PURE__*/
  messageDesc(file_sslsim_ssl_simulation_control, 0);

/**
 * ボールをテレポートする
 *
 * @generated from message sslsim.TeleportBall
 */
export type TeleportBall = Message<"sslsim.TeleportBall"> & {
  /**
   * x座標 [m]
   *
   * @generated from field: optional float x = 1;
   */
  x: number;

  /**
   * y座標 [m]
   *
   * @generated from field: optional float y = 2;
   */
  y: number;

  /**
   * z座標（高さ）[m]
   *
   * @generated from field: optional float z = 3;
   */
  z: number;

  /**
   * x方向速度 [m/s]
   *
   * @generated from field: optional float vx = 4;
   */
  vx: number;

  /**
   * y方向速度 [m/s]
   *
   * @generated from field: optional float vy = 5;
   */
  vy: number;

  /**
   * z方向速度 [m/s]
   *
   * @generated from field: optional float vz = 6;
   */
  vz: number;

  /**
   * 衝突を避けて安全にテレポートする
   *
   * @generated from field: optional bool teleport_safely = 7 [default = false];
   */
  teleportSafely: boolean;

  /**
   * ボールが転がるよう角速度を調整する
   *
   * @generated from field: optional bool roll = 8 [default = false];
   */
  roll: boolean;

  /**
   * テレポートの代わりに力を加えてボールを移動する（velocityは無視される）
   *
   * @generated from field: optional bool by_force = 9 [default = false];
   */
  byForce: boolean;
};

/**
 * ボールをテレポートする
 *
 * @generated from message sslsim.TeleportBall
 */
export type TeleportBallJson = {
  /**
   * x座標 [m]
   *
   * @generated from field: optional float x = 1;
   */
  x?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * y座標 [m]
   *
   * @generated from field: optional float y = 2;
   */
  y?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * z座標（高さ）[m]
   *
   * @generated from field: optional float z = 3;
   */
  z?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * x方向速度 [m/s]
   *
   * @generated from field: optional float vx = 4;
   */
  vx?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * y方向速度 [m/s]
   *
   * @generated from field: optional float vy = 5;
   */
  vy?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * z方向速度 [m/s]
   *
   * @generated from field: optional float vz = 6;
   */
  vz?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * 衝突を避けて安全にテレポートする
   *
   * @generated from field: optional bool teleport_safely = 7 [default = false];
   */
  teleportSafely?: boolean;

  /**
   * ボールが転がるよう角速度を調整する
   *
   * @generated from field: optional bool roll = 8 [default = false];
   */
  roll?: boolean;

  /**
   * テレポートの代わりに力を加えてボールを移動する（velocityは無視される）
   *
   * @generated from field: optional bool by_force = 9 [default = false];
   */
  byForce?: boolean;
};

/**
 * Describes the message sslsim.TeleportBall.
 * Use `create(TeleportBallSchema)` to create a new message.
 */
export const TeleportBallSchema: GenMessage<TeleportBall, TeleportBallJson> = /*@__PURE__*/
  messageDesc(file_sslsim_ssl_simulation_control, 1);

/**
 * ロボットをテレポートする
 *
 * @generated from message sslsim.TeleportRobot
 */
export type TeleportRobot = Message<"sslsim.TeleportRobot"> & {
  /**
   * テレポート対象のロボットID
   *
   * @generated from field: required sslsim.SslSimRobotId id = 1;
   */
  id?: SslSimRobotId;

  /**
   * x座標 [m]
   *
   * @generated from field: optional float x = 2;
   */
  x: number;

  /**
   * y座標 [m]
   *
   * @generated from field: optional float y = 3;
   */
  y: number;

  /**
   * 向き [rad]（x軸から反時計回り）
   *
   * @generated from field: optional float orientation = 4;
   */
  orientation: number;

  /**
   * x方向グローバル速度 [m/s]
   *
   * @generated from field: optional float v_x = 5 [default = 0];
   */
  vX: number;

  /**
   * y方向グローバル速度 [m/s]
   *
   * @generated from field: optional float v_y = 6 [default = 0];
   */
  vY: number;

  /**
   * 角速度 [rad/s]
   *
   * @generated from field: optional float v_angular = 7 [default = 0];
   */
  vAngular: number;

  /**
   * trueでフィールドに追加、falseで除去
   *
   * @generated from field: optional bool present = 8;
   */
  present: boolean;

  /**
   * テレポートの代わりに力を加えてロボットを移動する（velocityは無視される）
   *
   * @generated from field: optional bool by_force = 9 [default = false];
   */
  byForce: boolean;
};

/**
 * ロボットをテレポートする
 *
 * @generated from message sslsim.TeleportRobot
 */
export type TeleportRobotJson = {
  /**
   * テレポート対象のロボットID
   *
   * @generated from field: required sslsim.SslSimRobotId id = 1;
   */
  id?: SslSimRobotIdJson;

  /**
   * x座標 [m]
   *
   * @generated from field: optional float x = 2;
   */
  x?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * y座標 [m]
   *
   * @generated from field: optional float y = 3;
   */
  y?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * 向き [rad]（x軸から反時計回り）
   *
   * @generated from field: optional float orientation = 4;
   */
  orientation?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * x方向グローバル速度 [m/s]
   *
   * @generated from field: optional float v_x = 5 [default = 0];
   */
  vX?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * y方向グローバル速度 [m/s]
   *
   * @generated from field: optional float v_y = 6 [default = 0];
   */
  vY?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * 角速度 [rad/s]
   *
   * @generated from field: optional float v_angular = 7 [default = 0];
   */
  vAngular?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * trueでフィールドに追加、falseで除去
   *
   * @generated from field: optional bool present = 8;
   */
  present?: boolean;

  /**
   * テレポートの代わりに力を加えてロボットを移動する（velocityは無視される）
   *
   * @generated from field: optional bool by_force = 9 [default = false];
   */
  byForce?: boolean;
};

/**
 * Describes the message sslsim.TeleportRobot.
 * Use `create(TeleportRobotSchema)` to create a new message.
 */
export const TeleportRobotSchema: GenMessage<TeleportRobot, TeleportRobotJson> = /*@__PURE__*/
  messageDesc(file_sslsim_ssl_simulation_control, 2);

/**
 * シミュレーション状態を制御する
 *
 * @generated from message sslsim.SimulatorControl
 */
export type SimulatorControl = Message<"sslsim.SimulatorControl"> & {
  /**
   * ボールをテレポートする
   *
   * @generated from field: optional sslsim.TeleportBall teleport_ball = 1;
   */
  teleportBall?: TeleportBall;

  /**
   * ロボットをテレポートする（複数可）
   *
   * @generated from field: repeated sslsim.TeleportRobot teleport_robot = 2;
   */
  teleportRobot: TeleportRobot[];

  /**
   * シミュレーション速度倍率を変更する
   *
   * @generated from field: optional float simulation_speed = 3;
   */
  simulationSpeed: number;
};

/**
 * シミュレーション状態を制御する
 *
 * @generated from message sslsim.SimulatorControl
 */
export type SimulatorControlJson = {
  /**
   * ボールをテレポートする
   *
   * @generated from field: optional sslsim.TeleportBall teleport_ball = 1;
   */
  teleportBall?: TeleportBallJson;

  /**
   * ロボットをテレポートする（複数可）
   *
   * @generated from field: repeated sslsim.TeleportRobot teleport_robot = 2;
   */
  teleportRobot?: TeleportRobotJson[];

  /**
   * シミュレーション速度倍率を変更する
   *
   * @generated from field: optional float simulation_speed = 3;
   */
  simulationSpeed?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message sslsim.SimulatorControl.
 * Use `create(SimulatorControlSchema)` to create a new message.
 */
export const SimulatorControlSchema: GenMessage<SimulatorControl, SimulatorControlJson> = /*@__PURE__*/
  messageDesc(file_sslsim_ssl_simulation_control, 3);

/**
 * クライアントからシミュレータへのコマンド
 *
 * @generated from message sslsim.SimulatorCommand
 */
export type SimulatorCommand = Message<"sslsim.SimulatorCommand"> & {
  /**
   * シミュレーション状態の制御
   *
   * @generated from field: optional sslsim.SimulatorControl control = 1;
   */
  control?: SimulatorControl;
};

/**
 * クライアントからシミュレータへのコマンド
 *
 * @generated from message sslsim.SimulatorCommand
 */
export type SimulatorCommandJson = {
  /**
   * シミュレーション状態の制御
   *
   * @generated from field: optional sslsim.SimulatorControl control = 1;
   */
  control?: SimulatorControlJson;
};

/**
 * Describes the message sslsim.SimulatorCommand.
 * Use `create(SimulatorCommandSchema)` to create a new message.
 */
export const SimulatorCommandSchema: GenMessage<SimulatorCommand, SimulatorCommandJson> = /*@__PURE__*/
  messageDesc(file_sslsim_ssl_simulation_control, 4);

/**
 * チームの識別子（gameController.Team と同一のワイヤーフォーマット）
 *
 * @generated from enum sslsim.SslSimTeam
 */
export enum SslSimTeam {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: YELLOW = 1;
   */
  YELLOW = 1,

  /**
   * @generated from enum value: BLUE = 2;
   */
  BLUE = 2,
}

/**
 * チームの識別子（gameController.Team と同一のワイヤーフォーマット）
 *
 * @generated from enum sslsim.SslSimTeam
 */
export type SslSimTeamJson = "UNKNOWN" | "YELLOW" | "BLUE";

/**
 * Describes the enum sslsim.SslSimTeam.
 */
export const SslSimTeamSchema: GenEnum<SslSimTeam, SslSimTeamJson> = /*@__PURE__*/
  enumDesc(file_sslsim_ssl_simulation_control, 0);

