// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sslsim/ssl_simulation_control.proto

package sslsim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// チームの識別子（gameController.Team と同一のワイヤーフォーマット）
type SslSimTeam int32

const (
	SslSimTeam_UNKNOWN SslSimTeam = 0
	SslSimTeam_YELLOW  SslSimTeam = 1
	SslSimTeam_BLUE    SslSimTeam = 2
)

// Enum value maps for SslSimTeam.
var (
	SslSimTeam_name = map[int32]string{
		0: "UNKNOWN",
		1: "YELLOW",
		2: "BLUE",
	}
	SslSimTeam_value = map[string]int32{
		"UNKNOWN": 0,
		"YELLOW":  1,
		"BLUE":    2,
	}
)

func (x SslSimTeam) Enum() *SslSimTeam {
	p := new(SslSimTeam)
	*p = x
	return p
}

func (x SslSimTeam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SslSimTeam) Descriptor() protoreflect.EnumDescriptor {
	return file_sslsim_ssl_simulation_control_proto_enumTypes[0].Descriptor()
}

func (SslSimTeam) Type() protoreflect.EnumType {
	return &file_sslsim_ssl_simulation_control_proto_enumTypes[0]
}

func (x SslSimTeam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SslSimTeam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SslSimTeam(num)
	return nil
}

// Deprecated: Use SslSimTeam.Descriptor instead.
func (SslSimTeam) EnumDescriptor() ([]byte, []int) {
	return file_sslsim_ssl_simulation_control_proto_rawDescGZIP(), []int{0}
}

// ロボットの識別子（gameController.BotId と同一のワイヤーフォーマット）
type SslSimRobotId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Team          *SslSimTeam            `protobuf:"varint,2,opt,name=team,enum=sslsim.SslSimTeam" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SslSimRobotId) Reset() {
	*x = SslSimRobotId{}
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SslSimRobotId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SslSimRobotId) ProtoMessage() {}

func (x *SslSimRobotId) ProtoReflect() protoreflect.Message {
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SslSimRobotId.ProtoReflect.Descriptor instead.
func (*SslSimRobotId) Descriptor() ([]byte, []int) {
	return file_sslsim_ssl_simulation_control_proto_rawDescGZIP(), []int{0}
}

func (x *SslSimRobotId) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SslSimRobotId) GetTeam() SslSimTeam {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return SslSimTeam_UNKNOWN
}

// ボールをテレポートする
type TeleportBall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// x座標 [m]
	X *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	// y座標 [m]
	Y *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	// z座標（高さ）[m]
	Z *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	// x方向速度 [m/s]
	Vx *float32 `protobuf:"fixed32,4,opt,name=vx" json:"vx,omitempty"`
	// y方向速度 [m/s]
	Vy *float32 `protobuf:"fixed32,5,opt,name=vy" json:"vy,omitempty"`
	// z方向速度 [m/s]
	Vz *float32 `protobuf:"fixed32,6,opt,name=vz" json:"vz,omitempty"`
	// 衝突を避けて安全にテレポートする
	TeleportSafely *bool `protobuf:"varint,7,opt,name=teleport_safely,json=teleportSafely,def=0" json:"teleport_safely,omitempty"`
	// ボールが転がるよう角速度を調整する
	Roll *bool `protobuf:"varint,8,opt,name=roll,def=0" json:"roll,omitempty"`
	// テレポートの代わりに力を加えてボールを移動する（velocityは無視される）
	ByForce       *bool `protobuf:"varint,9,opt,name=by_force,json=byForce,def=0" json:"by_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TeleportBall fields.
const (
	Default_TeleportBall_TeleportSafely = bool(false)
	Default_TeleportBall_Roll           = bool(false)
	Default_TeleportBall_ByForce        = bool(false)
)

func (x *TeleportBall) Reset() {
	*x = TeleportBall{}
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeleportBall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportBall) ProtoMessage() {}

func (x *TeleportBall) ProtoReflect() protoreflect.Message {
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportBall.ProtoReflect.Descriptor instead.
func (*TeleportBall) Descriptor() ([]byte, []int) {
	return file_sslsim_ssl_simulation_control_proto_rawDescGZIP(), []int{1}
}

func (x *TeleportBall) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *TeleportBall) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *TeleportBall) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *TeleportBall) GetVx() float32 {
	if x != nil && x.Vx != nil {
		return *x.Vx
	}
	return 0
}

func (x *TeleportBall) GetVy() float32 {
	if x != nil && x.Vy != nil {
		return *x.Vy
	}
	return 0
}

func (x *TeleportBall) GetVz() float32 {
	if x != nil && x.Vz != nil {
		return *x.Vz
	}
	return 0
}

func (x *TeleportBall) GetTeleportSafely() bool {
	if x != nil && x.TeleportSafely != nil {
		return *x.TeleportSafely
	}
	return Default_TeleportBall_TeleportSafely
}

func (x *TeleportBall) GetRoll() bool {
	if x != nil && x.Roll != nil {
		return *x.Roll
	}
	return Default_TeleportBall_Roll
}

func (x *TeleportBall) GetByForce() bool {
	if x != nil && x.ByForce != nil {
		return *x.ByForce
	}
	return Default_TeleportBall_ByForce
}

// ロボットをテレポートする
type TeleportRobot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// テレポート対象のロボットID
	Id *SslSimRobotId `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// x座標 [m]
	X *float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	// y座標 [m]
	Y *float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	// 向き [rad]（x軸から反時計回り）
	Orientation *float32 `protobuf:"fixed32,4,opt,name=orientation" json:"orientation,omitempty"`
	// x方向グローバル速度 [m/s]
	VX *float32 `protobuf:"fixed32,5,opt,name=v_x,json=vX,def=0" json:"v_x,omitempty"`
	// y方向グローバル速度 [m/s]
	VY *float32 `protobuf:"fixed32,6,opt,name=v_y,json=vY,def=0" json:"v_y,omitempty"`
	// 角速度 [rad/s]
	VAngular *float32 `protobuf:"fixed32,7,opt,name=v_angular,json=vAngular,def=0" json:"v_angular,omitempty"`
	// trueでフィールドに追加、falseで除去
	Present *bool `protobuf:"varint,8,opt,name=present" json:"present,omitempty"`
	// テレポートの代わりに力を加えてロボットを移動する（velocityは無視される）
	ByForce       *bool `protobuf:"varint,9,opt,name=by_force,json=byForce,def=0" json:"by_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TeleportRobot fields.
const (
	Default_TeleportRobot_VX       = float32(0)
	Default_TeleportRobot_VY       = float32(0)
	Default_TeleportRobot_VAngular = float32(0)
	Default_TeleportRobot_ByForce  = bool(false)
)

func (x *TeleportRobot) Reset() {
	*x = TeleportRobot{}
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeleportRobot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportRobot) ProtoMessage() {}

func (x *TeleportRobot) ProtoReflect() protoreflect.Message {
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportRobot.ProtoReflect.Descriptor instead.
func (*TeleportRobot) Descriptor() ([]byte, []int) {
	return file_sslsim_ssl_simulation_control_proto_rawDescGZIP(), []int{2}
}

func (x *TeleportRobot) GetId() *SslSimRobotId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TeleportRobot) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *TeleportRobot) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *TeleportRobot) GetOrientation() float32 {
	if x != nil && x.Orientation != nil {
		return *x.Orientation
	}
	return 0
}

func (x *TeleportRobot) GetVX() float32 {
	if x != nil && x.VX != nil {
		return *x.VX
	}
	return Default_TeleportRobot_VX
}

func (x *TeleportRobot) GetVY() float32 {
	if x != nil && x.VY != nil {
		return *x.VY
	}
	return Default_TeleportRobot_VY
}

func (x *TeleportRobot) GetVAngular() float32 {
	if x != nil && x.VAngular != nil {
		return *x.VAngular
	}
	return Default_TeleportRobot_VAngular
}

func (x *TeleportRobot) GetPresent() bool {
	if x != nil && x.Present != nil {
		return *x.Present
	}
	return false
}

func (x *TeleportRobot) GetByForce() bool {
	if x != nil && x.ByForce != nil {
		return *x.ByForce
	}
	return Default_TeleportRobot_ByForce
}

// シミュレーション状態を制御する
type SimulatorControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ボールをテレポートする
	TeleportBall *TeleportBall `protobuf:"bytes,1,opt,name=teleport_ball,json=teleportBall" json:"teleport_ball,omitempty"`
	// ロボットをテレポートする（複数可）
	TeleportRobot []*TeleportRobot `protobuf:"bytes,2,rep,name=teleport_robot,json=teleportRobot" json:"teleport_robot,omitempty"`
	// シミュレーション速度倍率を変更する
	SimulationSpeed *float32 `protobuf:"fixed32,3,opt,name=simulation_speed,json=simulationSpeed" json:"simulation_speed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulatorControl) Reset() {
	*x = SimulatorControl{}
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatorControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatorControl) ProtoMessage() {}

func (x *SimulatorControl) ProtoReflect() protoreflect.Message {
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatorControl.ProtoReflect.Descriptor instead.
func (*SimulatorControl) Descriptor() ([]byte, []int) {
	return file_sslsim_ssl_simulation_control_proto_rawDescGZIP(), []int{3}
}

func (x *SimulatorControl) GetTeleportBall() *TeleportBall {
	if x != nil {
		return x.TeleportBall
	}
	return nil
}

func (x *SimulatorControl) GetTeleportRobot() []*TeleportRobot {
	if x != nil {
		return x.TeleportRobot
	}
	return nil
}

func (x *SimulatorControl) GetSimulationSpeed() float32 {
	if x != nil && x.SimulationSpeed != nil {
		return *x.SimulationSpeed
	}
	return 0
}

// クライアントからシミュレータへのコマンド
type SimulatorCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// シミュレーション状態の制御
	Control       *SimulatorControl `protobuf:"bytes,1,opt,name=control" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulatorCommand) Reset() {
	*x = SimulatorCommand{}
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatorCommand) ProtoMessage() {}

func (x *SimulatorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_sslsim_ssl_simulation_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatorCommand.ProtoReflect.Descriptor instead.
func (*SimulatorCommand) Descriptor() ([]byte, []int) {
	return file_sslsim_ssl_simulation_control_proto_rawDescGZIP(), []int{4}
}

func (x *SimulatorCommand) GetControl() *SimulatorControl {
	if x != nil {
		return x.Control
	}
	return nil
}

var File_sslsim_ssl_simulation_control_proto protoreflect.FileDescriptor

const file_sslsim_ssl_simulation_control_proto_rawDesc = "" +
	"\n" +
	"#sslsim/ssl_simulation_control.proto\x12\x06sslsim\"G\n" +
	"\rSslSimRobotId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12&\n" +
	"\x04team\x18\x02 \x01(\x0e2\x12.sslsim.SslSimTeamR\x04team\"\xd5\x01\n" +
	"\fTeleportBall\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02vx\x18\x04 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x05 \x01(\x02R\x02vy\x12\x0e\n" +
	"\x02vz\x18\x06 \x01(\x02R\x02vz\x12.\n" +
	"\x0fteleport_safely\x18\a \x01(\b:\x05falseR\x0eteleportSafely\x12\x19\n" +
	"\x04roll\x18\b \x01(\b:\x05falseR\x04roll\x12 \n" +
	"\bby_force\x18\t \x01(\b:\x05falseR\abyForce\"\xf8\x01\n" +
	"\rTeleportRobot\x12%\n" +
	"\x02id\x18\x01 \x02(\v2\x15.sslsim.SslSimRobotIdR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12 \n" +
	"\vorientation\x18\x04 \x01(\x02R\vorientation\x12\x12\n" +
	"\x03v_x\x18\x05 \x01(\x02:\x010R\x02vX\x12\x12\n" +
	"\x03v_y\x18\x06 \x01(\x02:\x010R\x02vY\x12\x1e\n" +
	"\tv_angular\x18\a \x01(\x02:\x010R\bvAngular\x12\x18\n" +
	"\apresent\x18\b \x01(\bR\apresent\x12 \n" +
	"\bby_force\x18\t \x01(\b:\x05falseR\abyForce\"\xb6\x01\n" +
	"\x10SimulatorControl\x129\n" +
	"\rteleport_ball\x18\x01 \x01(\v2\x14.sslsim.TeleportBallR\fteleportBall\x12<\n" +
	"\x0eteleport_robot\x18\x02 \x03(\v2\x15.sslsim.TeleportRobotR\rteleportRobot\x12)\n" +
	"\x10simulation_speed\x18\x03 \x01(\x02R\x0fsimulationSpeed\"F\n" +
	"\x10SimulatorCommand\x122\n" +
	"\acontrol\x18\x01 \x01(\v2\x18.sslsim.SimulatorControlR\acontrol*/\n" +
	"\n" +
	"SslSimTeam\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x02B\x99\x01\n" +
	"\n" +
	"com.sslsimB\x19SslSimulationControlProtoP\x01Z8github.com/RoboCup-SSL/ssl-vision-client/internal/sslsim\xa2\x02\x03SXX\xaa\x02\x06Sslsim\xca\x02\x06Sslsim\xe2\x02\x12Sslsim\\GPBMetadata\xea\x02\x06Sslsim"

var (
	file_sslsim_ssl_simulation_control_proto_rawDescOnce sync.Once
	file_sslsim_ssl_simulation_control_proto_rawDescData []byte
)

func file_sslsim_ssl_simulation_control_proto_rawDescGZIP() []byte {
	file_sslsim_ssl_simulation_control_proto_rawDescOnce.Do(func() {
		file_sslsim_ssl_simulation_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sslsim_ssl_simulation_control_proto_rawDesc), len(file_sslsim_ssl_simulation_control_proto_rawDesc)))
	})
	return file_sslsim_ssl_simulation_control_proto_rawDescData
}

var file_sslsim_ssl_simulation_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sslsim_ssl_simulation_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sslsim_ssl_simulation_control_proto_goTypes = []any{
	(SslSimTeam)(0),          // 0: sslsim.SslSimTeam
	(*SslSimRobotId)(nil),    // 1: sslsim.SslSimRobotId
	(*TeleportBall)(nil),     // 2: sslsim.TeleportBall
	(*TeleportRobot)(nil),    // 3: sslsim.TeleportRobot
	(*SimulatorControl)(nil), // 4: sslsim.SimulatorControl
	(*SimulatorCommand)(nil), // 5: sslsim.SimulatorCommand
}
var file_sslsim_ssl_simulation_control_proto_depIdxs = []int32{
	0, // 0: sslsim.SslSimRobotId.team:type_name -> sslsim.SslSimTeam
	1, // 1: sslsim.TeleportRobot.id:type_name -> sslsim.SslSimRobotId
	2, // 2: sslsim.SimulatorControl.teleport_ball:type_name -> sslsim.TeleportBall
	3, // 3: sslsim.SimulatorControl.teleport_robot:type_name -> sslsim.TeleportRobot
	4, // 4: sslsim.SimulatorCommand.control:type_name -> sslsim.SimulatorControl
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sslsim_ssl_simulation_control_proto_init() }
func file_sslsim_ssl_simulation_control_proto_init() {
	if File_sslsim_ssl_simulation_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sslsim_ssl_simulation_control_proto_rawDesc), len(file_sslsim_ssl_simulation_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sslsim_ssl_simulation_control_proto_goTypes,
		DependencyIndexes: file_sslsim_ssl_simulation_control_proto_depIdxs,
		EnumInfos:         file_sslsim_ssl_simulation_control_proto_enumTypes,
		MessageInfos:      file_sslsim_ssl_simulation_control_proto_msgTypes,
	}.Build()
	File_sslsim_ssl_simulation_control_proto = out.File
	file_sslsim_ssl_simulation_control_proto_goTypes = nil
	file_sslsim_ssl_simulation_control_proto_depIdxs = nil
}
